---
apiVersion: database.govsvc.uk/v1beta1
kind: Postgres
metadata:
  name: postgres-sample
  labels:
    group.access.govsvc.uk: gsp.examples.test
spec:
  aws:
    instanceType: db.t3.medium
    instanceCount: 1
