{{- $clusterName := .Values.global.cluster.name }}
{{- $accountName := .Values.global.account.name }}
{{- range .Values.namespaces }}
{{- $ns := . }}
{{- $trustedGithubAccounts := list }}
{{- range $.Values.users }}
  {{- $user := . }}
  {{- range .roles }}
    {{- if eq .account $accountName }}
      {{- $trustedGithubAccounts = append $trustedGithubAccounts $user.github }}
    {{- end }}
  {{- end }}
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: {{ .name }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-allow-ingressgateway
  namespace: {{ .name }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          istio: ingressgateway
      namespaceSelector:
        matchLabels:
          namespace: istio-system
{{- if (default dict .ingress).enabled }}
    - podSelector:
        matchLabels:
          istio: {{ .name }}-ingressgateway
      namespaceSelector:
        matchLabels:
          namespace: {{ .name }}
{{- end }}
---
{{- if (default dict .ingress).enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-to-ingressgateway
  namespace: {{ .name }}
spec:
  podSelector:
    matchLabels:
      istio: {{ .name }}-ingressgateway
  ingress:
  - from: []
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: namespace-default
  namespace: {{ .name }}
spec:
  secretName: namespace-default-certificate
  dnsNames:
  - "{{ .name }}.{{ $.Values.global.cluster.domain }}"
  issuerRef:
    name: letsencrypt-r53
    kind: ClusterIssuer
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: namespace-default
  namespace: {{ .name }}
  annotations:
    externaldns.k8s.io/namespace: {{ .name }}
spec:
  selector:
    istio: {{ .name }}-ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: true
    hosts:
    - "{{ .name }}.{{ $.Values.global.cluster.domain }}"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: sds
      privateKey: sds
      credentialName: namespace-default-certificate
    hosts:
    - "{{ .name }}.{{ $.Values.global.cluster.domain }}"
---
{{- end }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-allow-prometheus
  namespace: {{ .name }}
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          namespace: gsp-system
      podSelector:
        matchLabels:
          app: prometheus
---
apiVersion: concourse.govsvc.uk/v1beta1
kind: Team
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: {{ trimPrefix (printf "%s-" $.Values.global.cluster.name) .name }}
  namespace: {{ .name }}
spec:
  roles:
  - name: owner
    local:
      users: ["pipeline-operator"]
  - name: pipeline-operator
    github:
      users: {{ (toJson (uniq $trustedGithubAccounts)) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: trusted-developers
  namespace: {{ .name }}
data:
  github-accounts: {{ (toJson (uniq $trustedGithubAccounts)) | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor
  namespace: {{ .name }}
data:
  root_key: {{ $.Values.notary.rootKey | b64enc }}
  ci_key: {{ $.Values.notary.delegationKey | b64enc }}
  harbor_username: {{ "admin" | b64enc }}
  harbor_password: {{ $.Values.harbor.harborAdminPassword | b64enc }}
  harbor_url: {{ (printf "https://registry.%s" $.Values.global.cluster.domain) | b64enc }}
  notary_root_passphrase: {{ $.Values.notary.rootPassphrase | b64enc }}
  notary_targets_passphrase: {{ $.Values.notary.targetsPassphrase | b64enc }}
  notary_snapshot_passphrase: {{ $.Values.notary.snapshotPassphrase | b64enc }}
  notary_delegation_passphrase: {{ $.Values.notary.delegationPassphrase | b64enc }}
  notary_url: {{ (printf "https://notary.%s" $.Values.global.cluster.domain) | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-creds
  namespace: {{ .name }}
data:
  .dockerconfigjson: {{ include "dockerconfig.json" $ | b64enc }}
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster
  namespace: {{ .name }}
data:
  name: {{ $.Values.global.cluster.name | b64enc }}
  domain: {{ $.Values.global.cluster.domain | b64enc }}
  cloudHsmIp: {{ $.Values.global.cloudHsm.ip | b64enc }}
  privateKey: {{ $.Values.global.cluster.privateKey | b64enc }}
  publicKey: {{ $.Values.global.cluster.publicKey | b64enc }}
  releaseVersion: {{ $.Values.global.cluster.releaseVersion | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: concourse
  namespace: {{ .name }}
data:
  github-resource-image: {{ $.Values.concourseResources.github.image.repository | b64enc }}
  github-resource-tag: {{ $.Values.concourseResources.github.image.tag | b64enc }}
  harbor-resource-image: {{ $.Values.concourseResources.harbor.image.repository | b64enc }}
  harbor-resource-tag: {{ $.Values.concourseResources.harbor.image.tag | b64enc }}
  task-toolbox-image: {{ $.Values.concourseResources.task.image.repository | b64enc }}
  task-toolbox-tag: {{ $.Values.concourseResources.task.image.tag | b64enc }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: concourse
  namespace: {{ .name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $.Release.Name }}-concourse-web
subjects:
- kind: ServiceAccount
  name: {{ $.Release.Name }}-concourse-web
  namespace: {{ $.Release.Namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: {{ .name }}
data:
  api-token: {{ $.Values.githubAPIToken | b64enc }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: namespace-deployer
  namespace: {{ .name }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .name }}-namespace-deployer
  namespace: {{ .name }}
  labels:
    gsp-binding: namespace-deployer
subjects:
- kind: ServiceAccount
  name: namespace-deployer
  namespace: {{ .name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .name }}-cluster-viewer
  labels:
    gsp-binding: cluster-viewer
subjects:
- kind: ServiceAccount
  name: namespace-deployer
  namespace: {{ .name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-viewer
---
apiVersion: v1
kind: Secret
metadata:
  name: namespace-deployer
  namespace: {{ .name }}
  annotations:
    "kubernetes.io/service-account.name": namespace-deployer
type: kubernetes.io/service-account-token
{{- if (eq (.scope | default "namespace") "cluster") }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-deployer
  namespace: {{ .name }}
  labels:
    gsp-account: cluster-deployer
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .name }}-cluster-deployer
  labels:
    gsp-binding: cluster-deployer
subjects:
- kind: ServiceAccount
  name: cluster-deployer
  namespace: {{ .name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-deployer
  namespace: {{ .name }}
  labels:
    gsp-secret: cluster-deployer
  annotations:
    "kubernetes.io/service-account.name": cluster-deployer
type: kubernetes.io/service-account-token
{{- end }}
{{- if .repository }}
---
apiVersion: concourse.govsvc.uk/v1beta1
kind: Pipeline
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: configure-namespace
  namespace: {{ .name }}
spec:
  exposed: true
  pipelineString: |
    resource_types:
    - name: github
      type: registry-image
      source:
        repository: "govsvc/concourse-github-resource"
        tag: "v0.0.2"
    resources:
    - name: src
      type: github
      icon: github-circle
      source:
        uri: "https://github.com/{{ .owner }}/{{ .repository }}.git"
        organization: {{ .owner }}
        branch: {{ .branch | default "master" | quote }}
        owner: {{ .owner }}
        repository: {{ .repository }}
        username: "re-autom8-ci"
        password: ((github.api-token))
        github_api_token: ((github.api-token))
        access_token: ((github.api-token))
        approvers: ((trusted-developers.github-accounts))
        required_approval_count: {{ required (printf "Missing requiredApprovalCount for namespace %s" .name) .requiredApprovalCount }}
        paths:
        - {{ .path | quote }}
    jobs:
    - name: apply
      serial: true
      plan:
      - get: src
        trigger: true
      - task: apply
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: {{ $.Values.concourseResources.task.image.repository | quote }}
              tag: {{ $.Values.concourseResources.task.image.tag | quote }}
          inputs:
          - name: src
          params:
            KUBERNETES_SERVICE_ACCOUNT: (({{ .scope | default "namespace" }}-deployer))
            KUBERNETES_TOKEN: (({{ .scope | default "namespace" }}-deployer.token))
            KUBERNETES_API: kubernetes.default.svc
            RELEASE_NAMESPACE: (({{ .scope | default "namespace" }}-deployer.namespace))
            PATH_TO_MANIFESTS: {{ .path | quote }}
            SRC_URI: {{ .uri }}
            SCOPE: {{ .scope | default "namespace" }}
          run:
            path: /bin/bash
            args:
            - -eu
            - -c
            - |
              echo "this job will populate the namespace with kubeyaml found in repository ${SRC_URI} at path ${PATH_TO_MANIFESTS}..."
              if [[ "${SCOPE}" == "cluster" ]]; then
                echo "deployer has cluster scope (can deploy anywhere)"
                NS_ARGS=""
              elif [[ "${SCOPE}" == "namespace" ]]; then
                echo "deployer has namespace scope (can only deploy to namespace)"
                NS_ARGS="-n ${RELEASE_NAMESPACE}"
              else
                echo "invalid scope '${SCOPE}' expected 'namespace' or 'cluster'"
                exit 1
              fi
              echo "configuring kubectl..."

              setup-kube-deployer
              kubectl config set-context deployer --namespace "${RELEASE_NAMESPACE}"

              echo "applying manifests from ${SRC_URI} at path ${PATH_TO_MANIFESTS} to ${RELEASE_NAMESPACE}"
              kubectl apply $NS_ARGS -R -f "./src/${PATH_TO_MANIFESTS}"
---
{{- end }}
{{- end }}
