{{ if .Values.gatekeeper.enabled }}
---
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: isolatetenantistioresources
spec:
  crd:
    spec:
      names:
        kind: IsolateTenantIstioResources
        listKind: IsolateTenantIstioResourcesList
        plural: isolatetenantistioresources
        singular: isolatetenantistioresources
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
{{ .Files.Get "policies/isolate-tenant-istio-resources/src.rego" | indent 8 }}
{{ end }}
