{{- if .Values.global.runningOnAws }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-service-operator
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}-service-operator"
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    control-plane: {{ .Release.Name }}-service-operator
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    matchLabels:
      control-plane: {{ .Release.Name }}-service-operator
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        control-plane: {{ .Release.Name }}-service-operator
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: "{{ .Values.serviceOperator.image.repository }}:{{ .Values.serviceOperator.image.tag }}"
        name: manager
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        env:
        - name: CLOUD_PROVIDER
          value: "aws"
        - name: CLUSTER_NAME
          value: {{ .Values.global.cluster.name | quote }}
        - name: AWS_OIDC_PROVIDER_URL
          value: {{ .Values.global.cluster.oidcProviderURL }}
        - name: AWS_OIDC_PROVIDER_ARN
          value: {{ .Values.global.cluster.oidcProviderARN }}
        - name: AWS_RDS_SECURITY_GROUP_ID
          value: {{ .Values.RDSFromWorkerSecurityGroup | quote }}
        - name: AWS_RDS_SUBNET_GROUP_NAME
          value: {{ .Values.privateDBSubnetGroup | quote }}
        - name: AWS_PRINCIPAL_SERVER_ROLE_ARN
          value: {{ .Values.serviceOperator.kiamServerRoleARN | quote }}
        - name: AWS_PRINCIPAL_PERMISSIONS_BOUNDARY_ARN
          value: {{ .Values.serviceOperator.permissionsBoundaryARN | quote }}
        resources:
          limits:
            cpu: 500m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 90Mi
      serviceAccountName: {{ template "serviceOperator.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
{{ end }}
