{{- if .Values.global.runningOnAws }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-service-operator-role
rules:
- apiGroups:
  - access.govsvc.uk
  resources:
  - principals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - access.govsvc.uk
  resources:
  - principals/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cache.govsvc.uk
  resources:
  - redis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.govsvc.uk
  resources:
  - redis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - database.govsvc.uk
  resources:
  - postgres
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.govsvc.uk
  resources:
  - postgres/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - queue.govsvc.uk
  resources:
  - sqs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - queue.govsvc.uk
  resources:
  - sqs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.govsvc.uk
  resources:
  - imagerepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.govsvc.uk
  resources:
  - imagerepositories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.govsvc.uk
  resources:
  - s3buckets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.govsvc.uk
  resources:
  - s3buckets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - secrets
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.istio.io
  resources:
  - serviceentries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
{{ end }}
