{{- if .Values.global.runningOnAws }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "serviceOperator.serviceAccountName" . }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceOperator.roleARN }}
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}-service-operator"
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    control-plane: {{ .Release.Name }}-service-operator
    controller-tools.k8s.io: "1.0"
{{ end }}
