global:
  istioNamespace: istio-system
  k8sIngressSelector: ingressgateway
  mtls:
    enabled: true
  proxy:
    accessLogFile: "/dev/stdout"
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY
  disablePolicyChecks: false
  # istio-galley is a validatingwebhook and istio-sidecar-injector is
  # a mutating webhook so we don't want them to
  # disappear. unfortunately the istio helm chart only lets you set
  # priorityClassName for all services at once
  priorityClassName: gsp-critical
  imagePullSecrets:
  - dockerhubpull

istio-cni:
  excludeNamespaces:
  - istio-system
  - kube-system
  - gsp-system

# https://github.com/helm/helm/issues/5135
# affects anything with a conditional in the istio chart's
# requirements.yaml.
# presented here exhaustively in the same order as they appear in
# the istio chart's requirements.yaml at the time of writing
sidecarInjectorWebhook:
  enabled: true
security:
  enabled: true
gateways:
  enabled: true
mixer:
  policy:
    enabled: true
  telemetry:
    enabled: true
nodeagent:
  enabled: false
pilot:
  enabled: true
grafana:
  enabled: false
prometheus:
  enabled: false
tracing:
  enabled: true
galley:
  enabled: true
kiali:
  enabled: true
istiocoredns:
  enabled: false
certmanager:
  enabled: false

# normal service can now resume
istio:
  ingress:
    enable: false
  galley:
    replicaCount: 2
  istio_cni:
    enabled: true
  tracing:
    enabled: true
  mixer:
    policy:
      replicaCount: 2
      autoscaleMin: 2
    telemetry:
      replicaCount: 2
      autoscaleMin: 2
  pilot:
    traceSampling: "5.0" # send 5% of traffic to jaeger
    replicaCount: 2
    autoscaleMin: 2
  prometheus:
    enabled: false
  gateways:
    istio-ingressgateway:
      enabled: false
  sidecarInjectorWebhook:
    replicaCount: 2
    enableNamespacesByDefault: true
    rewriteAppHTTPProbe: true
  kiali:
    enabled: true
    createDemoSecret: true # FIXME: probably not a good idea for prod!
    prometheusAddr: http://gsp-prometheus-operator-prometheus.gsp-system:9090
