global:
  istioNamespace: istio-system
  k8sIngressSelector: ingressgateway
  mtls:
    enabled: true
  proxy:
    accessLogFile: "/dev/stdout"
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY
  disablePolicyChecks: false

istio-cni:
  tag: release-1.1-20190808-09-16
  excludeNamespaces:
  - istio-system
  - kube-system
  - gsp-system
istio-init:
  certmanager:
    enabled: true

# https://github.com/helm/helm/issues/5135
# affects anything with a conditional in the istio chart's
# requirements.yaml.
# presented here exhaustively in the same order as they appear in
# the istio chart's requirements.yaml at the time of writing
sidecarInjectorWebhook:
  enabled: true
security:
  enabled: true
gateways:
  enabled: true
mixer:
  policy:
    enabled: true
  telemetry:
    enabled: true
nodeagent:
  enabled: false
pilot:
  enabled: true
grafana:
  enabled: false
prometheus:
  enabled: false
tracing:
  enabled: true
galley:
  enabled: true
kiali:
  enabled: true
istiocoredns:
  enabled: false
certmanager:
  enabled: true

# normal service can now resume
istio:
  ingress:
    enable: false
  certmanager:
    enabled: true
  istio_cni:
    enabled: true
  tracing:
    enabled: true
  pilot:
    traceSampling: "100.0"
  prometheus:
    enabled: false
  gateways:
    istio-ingressgateway:
      enabled: false
  sidecarInjectorWebhook:
    enableNamespacesByDefault: true
    rewriteAppHTTPProbe: true
  kiali:
    enabled: true
    createDemoSecret: true # FIXME: probably not a good idea for prod!
    prometheusAddr: http://gsp-prometheus-operator-prometheus.gsp-system:9090
