{{ if .Values.gatekeeper.enabled }}
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RequireImageDigest
metadata:
  name: digests-on-internal-registry
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    registry: "registry.{{ .Values.global.cluster.domain }}"
    aws_account_id: {{ .Values.global.account.id | quote }}
{{ end }}
