apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: {{ .Release.Name }}-egress
spec:
  order: 100
  types:
  - Egress
  egress:
  - action: Deny
    protocol: TCP
    source:
      selector: talksToHsm != 'true'
    destination:
      nets:
      - {{ .Values.global.cloudHsm.ip }}/32
      ports:
      - 2223
      - 2224
      - 2225
  - action: Deny
    protocol: TCP
    source:
      namespaceSelector: talksToHsm != 'true'
    destination:
      nets:
      - {{ .Values.global.cloudHsm.ip }}/32
      ports:
      - 2223
      - 2224
      - 2225
  - action: Deny
    protocol: TCP
    source:
      selector: talksToAWSMetadataService != 'true'
    destination:
      nets:
      - 169.254.169.254/32
  - action: Deny
    protocol: TCP
    source:
      namespaceSelector: talksToAWSMetadataService != 'true'
    destination:
      nets:
      - 169.254.169.254/32
  - action: Allow

