apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-r53
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: automate-team@digital.cabinet-office.gov.uk
    privateKeySecretRef:
      name: letsencrypt-r53
    solvers:
    - selector: {}
      dns01:
        route53:
          region: eu-west-2
