{{- if .Values.global.runningOnAws }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ include "gsp-cluster.fullname" . }}-aws-sts
  labels:
    app.kubernetes.io/name: {{ include "gsp-cluster.name" . }}-aws-sts
    helm.sh/chart: {{ include "gsp-cluster.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  hosts:
  - sts.amazonaws.com
  - sts.eu-west-2.amazonaws.com
  ports:
  - name: https
    number: 443
    protocol: TLS
  location: MESH_EXTERNAL
  resolution: DNS
{{- end }}
