dependencies:
  - name: "cluster-autoscaler"
    version: 5.1.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: global.runningOnAws
  - name: "concourse"
    version: 8.2.6
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: global.concourse.enabled
  - name: "fluentd-cloudwatch"
    version: 0.9.1
    repository: https://kubernetes-charts-incubator.storage.googleapis.com/
    condition: global.runningOnAws
  - name: "harbor"
    version: 1.1.3
    repository: https://helm.goharbor.io/
    condition: global.harbor.enabled
  - name: "kiam"
    version: 2.5.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: global.runningOnAws
  - name: "cert-manager"
    version: v0.11.0
    repository: https://charts.jetstack.io/
