apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-r53
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: daniel.blair@digital.cabinet-office.gov.uk
    privateKeySecretRef:
      name: letsencrypt-r53
    dns01:
      providers:
      - name: route53
        route53:
          region: eu-west-2
