apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gsp-canary.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gsp-canary.name" . }}
    helm.sh/chart: {{ include "gsp-canary.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gsp-canary.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gsp-canary.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: {{ .Release.Name }}-{{ include "gsp-canary.name" . }}
        version: {{ .Chart.AppVersion | quote }}
{{- with .Values.annotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.canary.image.repository }}:{{ .Values.canary.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: CHART_COMMIT_TIMESTAMP
              value: "{{ .Values.canary.chartCommitTimestamp }}"
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: http
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
