apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "gsp-canary.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gsp-canary.name" . }}
    helm.sh/chart: {{ include "gsp-canary.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  hosts:
  - canary.{{ .Release.Namespace }}.{{ .Values.global.cluster.domain }}
  gateways:
  - {{ include "gsp-canary.fullname" . }}-ingress
  http:
    - route:
      - destination:
          host: {{ include "gsp-canary.fullname" . }}
          port:
            number: {{ .Values.service.port }}
