---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: auditor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: auditor
subjects:
- kind: Group
  name: "aws-iam:authenticated-users"
  apiGroup: rbac.authorization.k8s.io
