apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
  {{- range .Values.bootstrapRoleARNs }}
    - rolearn: {{ . | quote }}
      username: system:node:{{ "{{" }}EC2PrivateDNSName{{ "}}" }}
      groups:
        - system:bootstrappers
        - system:nodes
  {{- end }}
  {{- range .Values.adminRoleARNs }}
    - rolearn: {{ . | quote }}
      username: admin:{{ "{{" }}SessionName{{ "}}" }}
      groups:
        - system:masters
  {{- end }}
  {{- range .Values.users }}
    - rolearn: {{ .roleARN | quote }}
      username: {{ .name }}
      groups:
        - aws-iam:authenticated-users
        {{- range .roles }}
        {{- if .namespace }}
        {{- if eq "operator" .role }}
        - {{ .namespace }}-operators
        {{- end }}
        {{- else }}
        {{- if eq "admin" .role }}
        - system:masters
        {{- end }}
        {{- end }}
        {{- end }}
  {{- end }}
