---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gsp-default-psp
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gsp-default-psp
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:authenticated
