---
apiVersion: v1
kind: Namespace
metadata:
  name: gsp-system
  labels:
    namespace: gsp-system
    istio-injection: disabled
    control-plane: "true"
    talksToAWSMetadataService: "true"
{{ if .Values.global.cloudHsm.public }}
    talksToHsm: "true"
{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: dockerhubpull
  namespace: gsp-system
data:
  .dockerconfigjson: {{ .Values.global.dockerHubCredentials | b64enc }}
type: kubernetes.io/dockerconfigjson
