---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    namespace: istio-system
    istio-injection: disabled
    istio: system
---
apiVersion: v1
kind: Secret
metadata:
  name: dockerhubpull
  namespace: istio-system
data:
  .dockerconfigjson: {{ .Values.global.dockerHubCredentials }}
type: kubernetes.io/dockerconfigjson
