{{- range .Values.namespaces }}
{{- $defaultedPermittedRolesRegex := .permittedRolesRegex | default "^$" }}
{{- $permittedRolesRegex := printf "%s|^svcop-%s-%s-.*$|^%s-%s-external-dns$" $defaultedPermittedRolesRegex $.Values.global.cluster.name .name $.Values.global.cluster.name .name }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
  labels:
    namespace: {{ .name }}
{{- if .talksToHsm }}
    talksToHsm: "true"
{{- end }}
{{- if .talksToPsn }}
    talksToPsn: "true"
{{- end }}
  annotations:
    iam.amazonaws.com/permitted: {{ $permittedRolesRegex | quote }}
{{- end }}
