{{- range .Values.namespaces }}
{{- $defaultedPermittedRolesRegex := .permittedRolesRegex | default "^$" }}
{{- $permittedRolesRegex := printf "%s|^svcop-%s-%s-.*$" $defaultedPermittedRolesRegex $.Values.global.cluster.name .name }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
  labels:
    namespace: {{ .name }}
  annotations:
    iam.amazonaws.com/permitted: {{ $permittedRolesRegex | quote }}
{{- end }}
