{{- range .Values.namespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
  labels:
    namespace: {{ .name }}
{{- if .talksToHsm }}
    talksToHsm: "true"
{{- end }}
{{- if .talksToPsn }}
    talksToPsn: "true"
{{- end }}
{{- end }}
